name: Build and Test

# This workflow will run on every push to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Test Java Services
        run: |
          ./services/price-producer/mvnw -B -f ./services/price-producer/pom.xml test
          ./services/price-streamer/mvnw -B -f ./services/price-streamer/pom.xml test

      - name: Install Python Dependencies
        run: pip install -r ./services/ml-service/requirements.txt

      # Note: Add Python tests here in the future if you have them
      # For example:
      # - name: Run Python Tests
      #   run: python -m pytest ./services/ml-service

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker build -t itachi21113/price-producer ./services/price-producer
          docker build -t itachi21113/price-streamer ./services/price-streamer
          docker build -t itachi21113/ml-service ./services/ml-service
          docker build -t itachi21113/frontend ./frontend          
          docker push itachi21113/price-producer
          docker push itachi21113/price-streamer
          docker push itachi21113/ml-service
          docker push itachi21113/frontend